import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import type { SpaceApplyBundle } from "@murrmure/contracts";
import { compileStepContractCatalog } from "./step-contract-compile.js";

export const SPACE_BRIEFING_REL_PATH = join(".mrmr.temp", "briefing.md");

export function spaceBriefingAbsPath(space_root: string): string {
  return join(space_root, SPACE_BRIEFING_REL_PATH);
}

const MCP_TOOLS = [
  "murrmure_resolve_step",
  "murrmure_wait_for_run",
  "murrmure_list_step_contracts",
  "murrmure_get_run",
  "murrmure_create_run",
  "murrmure_invoke_action",
  "murrmure_space_status",
];

export function renderSpaceBriefingMarkdown(
  bundle: SpaceApplyBundle,
  space_id: string,
): string {
  const lines: string[] = [
    "# Space briefing (generated by `mrmr space apply`)",
    "",
    "Use this file for layout and flow structure. Do not re-scan the whole repo unless a step requires it.",
    "",
    `- **Space:** ${space_id}`,
    `- **Briefing path:** ${SPACE_BRIEFING_REL_PATH}`,
    "",
    "## Key paths",
    "",
    "- `murrmure/actions.yaml` — shell action prompts",
    "- `murrmure/flows/*/flow.manifest.yaml` — step contracts",
    "- `murrmure/views/` — custom human-facing UI",
    "- `specs/current/` — active spec markdown",
    "- `specs/archive/` — completed specs",
    "- `index.html` — static site root (preview-review tutorial)",
    "- `agent.md` — agent conventions",
    "- `skills/` — step skills (e.g. `feature-build`)",
    "",
    "## Murrmure MCP tools",
    "",
    ...MCP_TOOLS.map((t) => `- \`${t}\``),
    "",
    "## Actions",
    "",
  ];

  const actionEntries = Object.entries(bundle.actions?.file?.actions ?? {});
  for (const [name, action] of actionEntries) {
    lines.push(`- **${name}** (${action.executor ?? "shell"})`);
  }
  if (actionEntries.length === 0) {
    lines.push("- _(none indexed)_");
  }

  lines.push("", "## Flows", "");

  for (const flow of bundle.flows ?? []) {
    const name = flow.manifest?.name ?? flow.flow_id;
    lines.push(`### ${name} (\`${flow.flow_id}\`)`);
    const steps = flow.manifest?.steps ?? [];
    for (const step of steps) {
      const sid = typeof step === "object" && step && "id" in step ? String(step.id) : "?";
      const exec =
        typeof step === "object" && step && "executor" in step && step.executor
          ? ` → ${(step.executor as { action?: string }).action ?? "executor"}`
          : "";
      const view =
        typeof step === "object" && step && "presentation" in step && step.presentation
          ? ` [view: ${(step.presentation as { view?: string }).view}]`
          : "";
      lines.push(`- \`${sid}\`${exec}${view}`);
      const nested = typeof step === "object" && step && "steps" in step ? step.steps : undefined;
      if (Array.isArray(nested)) {
        for (const child of nested) {
          const cid = typeof child === "object" && child && "id" in child ? String(child.id) : "?";
          lines.push(`  - \`${sid}.${cid}\``);
        }
      }
    }
    const { catalog } = compileStepContractCatalog(flow.manifest, flow.flow_id);
    if (catalog?.graph_digest) {
      lines.push(`- catalog digest: \`${catalog.graph_digest.slice(0, 12)}…\``);
    }
    lines.push("");
  }

  return lines.join("\n").trim() + "\n";
}

export async function writeSpaceBriefingFile(
  space_root: string,
  bundle: SpaceApplyBundle,
  space_id: string,
): Promise<string> {
  const path = spaceBriefingAbsPath(space_root);
  await mkdir(dirname(path), { recursive: true });
  const markdown = renderSpaceBriefingMarkdown(bundle, space_id);
  await writeFile(path, markdown, "utf-8");
  return path;
}

export async function readSpaceBriefingExcerpt(
  space_root: string,
  maxChars = 12_000,
): Promise<string | undefined> {
  try {
    const raw = await readFile(spaceBriefingAbsPath(space_root), "utf-8");
    const trimmed = raw.trim();
    if (!trimmed) return undefined;
    if (trimmed.length <= maxChars) return trimmed;
    return `${trimmed.slice(0, maxChars)}\n\n…(briefing truncated)`;
  } catch {
    return undefined;
  }
}
